### ISSUE TITLE
Posting isnt possible when installed!

### ISSUE THREAD

**Issue by syntafin** [IsekaiDevPlugins/de.isekaidev.discord.wbbBridge#3]
After install, when I try to post a reply/new topic, a fatal error appears, for better describtion, see attachment/link:

[https://dl3.tengusystems.de/screenshot-double-spoiler.de 2017-07-06 18-50-02.png](http://syntaf.in/2tQLyBc)

**Comment by Akizo96** [comment]
After re-saving your options in your ACP it should work.
When not, can you please tell me what Plugins do you have installed that have to do with Discord

I will add a check if the variable is defined when i update the Discord API Package.

**Comment by syntafin** [comment]
Other plugins with Discord:
Discord API/Discord Login from iFy.re

**Comment by Akizo96** [comment]
Thats the problem, my plugins are not compatible with his plugins. You have to uninstall mine or his plugins.

**Comment by kevinboeger** [comment]
For me it doosent post also but i dont have other discord plugins then yours
